### ISSUE TITLE
Units used by the package

### ISSUE THREAD

**Issue by johnnymatt** [chenyk1990/pyekfmm#1]
Hi,

I was wondering whether my input units should be in km and seconds? Currently, I am using mm for distances and mm/s for velocities.

**Comment by chenyk1990** [comment]
Hi, Ioannis,

Thanks for your query. I think it just needs to be consistent; if you use
velocity in km/s, then your axis (ax,ay,az) needs to be in km; the same
goes for velocity in m/s.

Hope that helps,
YC

**Comment by johnnymatt** [comment]
Hi,

Thank you for the feedback.

Ioannis

**Comment by johnnymatt** [comment]
Thanks for the feedback,
